### PR TITLE
fix: update name and email from GitHub every sign-in

### LINKED ISSUE #173: Account names aren’t updated when a user changes their GitHub account’s name
Perhaps it should update on each sign in?

### PR DESCRIPTION
**Pull request by lucacasonato**
Previously we'd only sync name and email from GitHub on signup. We now do this in both signup, and signin.

Fixes #173

### CODE REVIEW

File: api/src/auth.rs [hunk 1]
```diff
@@ -156,28 +157,22 @@ async fn generate_access_token(
...
-
-      db.insert_user(user).await?.id
-    }
+  let new_user = NewUser {
+    name: name.as_str(),
+    email: gh_email.as_deref(),
+    avatar_url: gh_user.avatar_url.as_str(),
+    github_id: Some(gh_user.id),
+    is_blocked: false,
+    is_staff: false,
```
Comment (marvinhagemeister) [inline api/src/auth.rs:166]: I might be reading this wrong, wouldn't that mean we'd always set these two values to `false` regardless of whether the user is staff or is blocked upon login?

Comment (marvinhagemeister) [reply api/src/auth.rs:166]: oh good point!

**Review by marvinhagemeister — APPROVED** [review]
