### PR TITLE
fix: don't ban triple slash references inside of jsdoc comments

### LINKED ISSUE #409: "Triple slash directives that modify globals" incorrectly showing up when using triple slash directives in jsdocs
I think the title is pretty clear, this error is still holding back Astral from being published on the JSR. [Here's a failed run to look at](https://github.com/lino-levan/astral/actions/runs/8745910661/job/24001796000).

Here's the code it's incorrectly tripping over:
image

Reported over email and discord, but figured I'd open an issue.

### PR DESCRIPTION
**Pull request by lucacasonato**
Fixes #409

### CODE REVIEW

File: api/src/tarball.rs [hunk 1]
```diff
@@ -300,7 +300,7 @@ pub async fn process_tarball(
               ".".to_owned()
             } else {
               format!("./{}", sub_path)
-            }
+            }
```
Comment (marvinhagemeister) [inline api/src/tarball.rs:303]: nit: space https://www.youtube.com/watch?v=bZUpggRKOms

**Review by marvinhagemeister — APPROVED** [review]
